example/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'polls.views.index', name='index'),
    url(r'^poll/form$', 'polls.views.form', name='form'),
    url(r'^poll/create$', 'polls.views.create', name='create'),
    url(r'^poll/update/(?P<pk>\d+)$', 'polls.views.update', name='update'),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += patterns(
    '',
    url(
        r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}
    )
)

example/polls/models.py
import os

from django.db import models


class Poll(models.Model):
    def upload_to(self, filepath):
        filename = os.path.basename(filepath)
        return os.path.join('poll', filename)

    question = models.CharField(max_length=200)
    main_image = models.ImageField('main image', upload_to=upload_to)
    sub_image = models.ImageField('sub image', upload_to=upload_to, blank=True, null=True)

example/polls/forms.py
from django import forms

from models import Poll


class PollModelForm(forms.ModelForm):
    class Meta:
        model = Poll


class PollForm(forms.Form):
    question = forms.CharField(max_length=200)
    main_image = forms.ImageField()
    sub_image = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop('instance', None)
        super(PollForm, self).__init__(*args, **kwargs)

        if self.instance:
            self.fields['question'].initial = self.instance.question
            self.fields['image'].initial = self.instance.image

    def save(self, commit=True):
        poll = self.instance if self.instance else Poll()

        poll.question = self.cleaned_data['question']

        if self.cleaned_data['main_image'] is False:
            poll.main_image = None
        else:
            poll.main_image = self.cleaned_data['main_image']

        if self.cleaned_data['sub_image'] is False:
            poll.sub_image = None
        else:
            poll.sub_image = self.cleaned_data['sub_image']

        if commit:
            poll.save()

        return poll

example/polls/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from formpreview.views import CreateView, FormView, UpdateView

from forms import PollForm, PollModelForm
from models import Poll


class IndexView(ListView):
    queryset = Poll.objects.order_by('-pk')
    template_name = 'index.html'

index = IndexView.as_view()


class PollFormView(FormView):
    form_class = PollForm
    input_template = 'input.html'
    preview_template = 'preview.html'
    success_url = reverse_lazy('index')

    def done(self, form):
        form.save()
        return super(PollFormView, self).done(form)

form = PollFormView.as_view()


class PollCreateView(CreateView):
    form_class = PollModelForm
    input_template = 'input.html'
    preview_template = 'preview.html'
    success_url = reverse_lazy('index')

create = PollCreateView.as_view()


class PollUpdateView(UpdateView):
    queryset = Poll.objects.all()
    form_class = PollModelForm
    input_template = 'input.html'
    preview_template = 'preview.html'
    success_url = reverse_lazy('index')

update = PollUpdateView.as_view()

example/polls/templates/done.html
<html>
<head>
    <title>Done - Poll</title>
</head>
<body>
    <p>Done.</p>
</body>
</html>

example/polls/templates/index.html
<html>
<head>
    <title>Poll</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'form' %}">Form Preview</a></li>
        <li><a href="{% url 'create' %}">Create Form Preview</a></li>
    </ul>
    <table>
        <thead>
            <tr>
                <th>id</th>
                <th>question</th>
                <th>main image</th>
                <th>sub image</th>
            </tr>
        </thead>
        <tbody>
            {% for poll in poll_list %}
            <tr>
                <td><a href="{% url 'update' poll.pk %}">{{ poll.pk }}</a></td>
                <td>{{ poll.question }}</td>
                <td>
                    <a href="{{ poll.main_image.url }}"><img src="{{ poll.main_image.url }}" height="64"></a>
                </td>
                <td>
                    {% if poll.sub_image %}
                        <a href="{{ poll.sub_image.url }}"><img src="{{ poll.sub_image.url }}" height="64"></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

example/polls/templates/input.html
<html>
<head>
    <title>Create - Poll</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ cache_key }}
        <table>
            {{ form }}
        </table>
        <p><button type="submit" name="{{ stage_field }}" value="preview">Preview</button></p>
    </form>
</body>
</html>

example/polls/templates/preview.html
<html>
<head>
    <title>Preview - Poll</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ cache_key }}
        <table>
            {{ form.preview_as_table }}
        </table>
        <p>
            <button type="submit" name="{{ stage_field }}" value="back">Back</button>
            <button type="submit" name="{{ stage_field }}" value="post">Post</button>
        </p>
    </form>
</body>
</html>